// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StorageData.DBContext;

namespace StorageData.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("StorageData.Model.EventAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("FramesId");

                    b.Property<Guid?>("ParametersId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("FramesId");

                    b.HasIndex("ParametersId");

                    b.ToTable("EventAttributes");
                });

            modelBuilder.Entity("StorageData.Model.Frame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EventId");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("Frames");
                });

            modelBuilder.Entity("StorageData.Model.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("StorageData.Model.EventAttribute", b =>
                {
                    b.HasOne("StorageData.Model.Frame", "Frames")
                        .WithMany("EventAttributes")
                        .HasForeignKey("FramesId");

                    b.HasOne("StorageData.Model.Parameter", "Parameters")
                        .WithMany("EventAttributes")
                        .HasForeignKey("ParametersId");
                });
#pragma warning restore 612, 618
        }
    }
}
